### ISSUE TITLE
Feature Request: Support of Kustomize install

### ISSUE THREAD

**Issue by Kampe** [project-akri/akri#182]
**Is your feature request related to a problem? Please describe.**
Hello! 
deployment of our some workloads rely heavily on use of kustomize for installing tools and operators rather than using Helm.  

**Is your feature request related to a way you would like Akri extended? Please describe.**
yes, extending the paths for installation of Akri.

**Describe the solution you'd like**
the ability to run `kustomize build github.com/deislabs/akri` which would return a base manifest for installation purposes. 

**Describe alternatives you've considered**
using kustomize remote resources to manually install the CRD's and handlers and create a specific deployment. 

**Additional context**
Would require a kustomization.yaml file in the root of the directory that points at the already created helm yaml resources.

**Comment by bfjelds** [comment]
This sounds cool!

**Comment by Kampe** [comment]
Yes! I plan to here soon when we bring in and test akri on our edge deploys :)
