### ISSUE TITLE
More fully document Akri's build process

### ISSUE THREAD

**Issue by DazWilkin** [project-akri/akri#211]
**Is your feature request related to a problem? Please describe.**

There are many, independent but necessary changes required when extending Akri.

The [Development](./docs/development.md) doc does a good job but it is insufficient.

The build process is quite involved.

**Is your feature request related to a way you would like Akri extended? Please describe.**

More fully document the steps needed to extend Akri's build process with new components.

Use these documented steps as informal unit tests when changes are made to the build process.

Consider improvements to the build process reviewing the documented steps.

E.g. the Makefiles are very repetitive and would benefit from refactoring.

**Describe the solution you'd like**

I took a stab at documenting extending the build process for new components since I've just done this for the Webhook:

https://hackmd.io/@akri/S16Xoixyd

Feedback very welcome.

**Describe alternatives you've considered**

None.

**Additional context**

E.g. see https://github.com/deislabs/akri/pull/206

**Comment by kate-goldenring** [comment]
This issue brings up a good point: Akri's development documentation could be more organized and comprehensive. 
Currently Akri's main development document is: https://docs.akri.sh/development/development
We also have one focused on using our makefiles: https://docs.akri.sh/development/building
And then the additional documentation @DazWilkin provided above:  https://hackmd.io/@akri/S16Xoixyd
This documentation should be brought together and reorganized and put into [Akri's documentation repository](https://github.com/deislabs/akri-docs)
