### ISSUE TITLE
Support ONVIF cameras that require authentication

### ISSUE THREAD

**Issue by kate-goldenring** [project-akri/akri#250]
**Is your feature request related to a problem? Please describe.**
Our sample ONVIF broker currently does not support connecting to cameras that require authentication . This support should be added along with documentation on how to pass credentials.

**Describe the solution you'd like**
A solution should be proposed and made for passing unique credentials such as user/pass to brokers. One solution could be to use a ConfigMap. The ONVIF sample broker should be updated to optionally use authentication with the provided credentials. 

**Describe alternatives you've considered**
Credentials could be passed via kubernetes secrets mounted into broker Pods, but then all brokers would get the same credentials. All discovered IP cameras would need to accept the same user/pass which is unlikely and unsage.

**Additional context**
Credential passing is currently supported for OPC UA -- aided by the use of x.509v3 certificates which can have a common CA over standard user/pass; however, that is not a complete solution either. 
For [OPC UA](https://github.com/deislabs/akri/blob/main/docs/opcua-configuration.md), kubernetes Secrets containing an x.509 certificate for an OPC UA client and the associated certificate authority are [set in the broker PodSpec](https://github.com/deislabs/akri/blob/main/docs/proposals/credentials-passing.md#how-secrets-are-used-in-opc-ua) of a Configuration. However, this assumes that all discovered OPC UA servers have the same Certificate Authority as the certificate passed to the broker or have manually accepted the broker's client. It also means that all brokers have the same certificate, which is unideal. A configMap could also be leveraged by OPC UA to give brokers unique certificates. Or the OPC UA brokers could call out to a CA to get a signed certificate.

**Comment by kate-goldenring** [comment]
A little update here. I did some investigation into what ONVIF device management endpoints require authentication. The only endpoint that seems universally public is `GetSystemDateAndTime` which is why it is currently used for aliveness checks. On the other hand, cameras that require authentication are currently not discovered because Akri's ONVIF discovery handler calls the [`GetNetworkInterfaces` endpoint](https://www.onvif.org/ver10/device/wsdl/devicemgmt.wsdl) on the camera in order to receive IP and MAC address information for filtering. Since this endpoint is not publicly accessible, a `Received a response status of 401 Unauthorized, expected 200` error is returned and the camera is removed from the discovered list. Previously, we also called `GetScopes` which is also not publicly accessible; however, we were able to get scope information from the original discovery response to perform scope filtering. The question is whether we can find a similar work around for getting the device MAC address. This unique identifier is needed for creating a unique Akri Instance ID for the camera. 

**Options for supporting IP cameras with authentication**
1. Akri could support discovering cameras with auth right now by removing the option to filter by MAC address and making the identifier based off of camera name and ip; however, there would be a risk of name collisions. 
2. Akri could resolve the mac address of the cameras via a tool like `arp`; however, the `libpnet` crate appears to only support [`arp` for IPv4](https://github.com/libpnet/libpnet/blob/master/examples/arp_packet.rs#L17). There may be other crates out there to support getting the mac address of a device we can use. 
3. Design and implement a way to pass credentials to the Discovery Handler.

**Comment by jiria** [comment]
Another idea, use mac for ipv4, and ip for ipv6. If there are ipv6 cameras that use temporary ipv6 ips for privacy, or other non stable ipv6 addresses, we could revisit. But chances of ipv6 address conflict are low.

Re arp library, wondering if onvif discovery can only work on the same subnet or further, which would probably break arp discovery.

**Comment by agracey** [comment]
I had a thought about this where it might be interesting to use a pattern similar to cert-manager. This would allow a discovery handler to create a "creds request" then have the "auth-manager" component be able to reach out to a 3rd party auth location to request creds. 

These creds could be encrypted and stored in something like Vault instead of a secret. 

We are running into this general issue more frequently than just Akri (Metal^3 for example) so there's likely room for a 3rd party project to implement/standardize this pattern.

**Comment by kate-goldenring** [comment]
> I had a thought about this where it might be interesting to use a pattern similar to cert-manager. This would allow a discovery handler to create a "creds request" then have the "auth-manager" component be able to reach out to a 3rd party auth location to request creds.
> 
> These creds could be encrypted and stored in something like Vault instead of a secret.
> 
> We are running into this general issue more frequently than just Akri (Metal^3 for example) so there's likely room for a 3rd party project to implement/standardize this pattern.

@adithyaj has been also putting thought into this space. The model you describe @agracey sounds ideal where we could have various secret manager backends that the auth manager could reach out to. I also was curious as to whether we could use Dapr for this but haven't been able to set aside time to try it out.

**Comment by markwu010** [comment]
> A little update here. I did some investigation into what ONVIF device management endpoints require authentication. The only endpoint that seems universally public is `GetSystemDateAndTime` which is why it is currently used for aliveness checks. On the other hand, cameras that require authentication are currently not discovered because Akri's ONVIF discovery handler calls the [`GetNetworkInterfaces` endpoint](https://www.onvif.org/ver10/device/wsdl/devicemgmt.wsdl) on the camera in order to receive IP and MAC address information for filtering. Since this endpoint is not publicly accessible, a `Received a response status of 401 Unauthorized, expected 200` error is returned and the camera is removed from the discovered list. Previously, we also called `GetScopes` which is also not publicly accessible; however, we were able to get scope information from the original discovery response to perform scope filtering. The question is whether we can find a similar work around for getting the device MAC address. This unique identifier is needed for creating a unique Akri Instance ID for the camera.
> 
> **Options for supporting IP cameras with authentication**
> 
> 1. Akri could support discovering cameras with auth right now by removing the option to filter by MAC address and making the identifier based off of camera name and ip; however, there would be a risk of name collisions.
> 2. Akri could resolve the mac address of the cameras via a tool like `arp`; however, the `libpnet` crate appears to only support [`arp` for IPv4](https://github.com/libpnet/libpnet/blob/master/examples/arp_packet.rs#L17). There may be other crates out there to support getting the mac address of a device we can use.
> 3. Design and implement a way to pass credentials to the Discovery Handler.

@kate-goldenring Dear Kate:  **The idea is to keep discover() simple and just do discover() at a time. Therefore, shall we decouple the filtering logic to another request?** 
And a few thoughts built on possible options here
1. Removing the option to filter by MAC address in the current flow is a way to simplify the discover().  
    To avoid the risk of name collisions by "Scope and IP", **providing a unique identifier** in "Scopes" might be an option.
    e.g. onvif://www.onvif.org/name/GreatONVIFCamera  -> onvif://www.onvif.org/name/GreatONVIFCamera-deviceID
    or   onvif://www.onvif.org/name/GreatONVIFCamera-deviceID + onvif://www.onvif.org/location/locationSpecifier 
2. To get the user credentials in the discovery handler if we really need to do so, just like @agracey mentioned, create a "get creds request" in the discovery handler and delegating the job to the "auth-manager" component might be a way to support platform-agnostic solution.

**Comment by kate-goldenring** [comment]
We discussed this a little in our community meeting today. I think we need to get a unique identifier from the camera (without authentication) in order to have an identifier to pass to a registry to get credentials. Maybe we circle back to looking into how to use a tool like `arp` (or equivalent library) to get mac addresses

**Comment by markwu010** [comment]
@kate-goldenring Dear Kate, many thanks for the reply, not a problem, I know it's the holiday season around the end of the year. I hope you take some time to relax. 
Let's circle back to this.

> * It would be a fairly big rework to remove filtering logic from the gRPC `Discover` request since [the request passes the filters](https://github.com/project-akri/akri/blob/main/discovery-utils/proto/discovery.proto#L36). There doesnt seem to be a reason for the agent to do the filtering. It would duplicate a lot of work and potentially bloat the Agent.

---> oh, indeed, removing the filtering logic is a burdensome rework.
What if we keep the same [discover request](https://github.com/project-akri/akri/blob/7d35269eeb31c0281533380e5cdfc82a279131e1/discovery-utils/proto/discovery.proto#L36) interface
but do not support custom helm key: **onvif.configuration.discoveryDetails.macAddresses**.
As we know, to get a device macAddress via the ONVIF protocol needs the user credentials, which is a pinpoint so far.
Could we leverage **http://onvif_host/onvif/device_service** as an alternative to distinguish devices?
According to [ONVIF core spec](https://www.onvif.org/specs/core/ONVIF-Core-Specification.pdf) sec 5.1.1,
![image](https://user-images.githubusercontent.com/87466538/210513121-cd330d7f-0f81-4f21-999e-a7ec4d0f21c2.png)
To my understanding, the entry point for an ONVIF-compliant device is fixed to **http://onvif_host/onvif/device_service**, onvif_host can be either an ipv4 or ipv6 address.
And this entry point can be retrieved from the WS-discovery response(d:XAddrs) as well(here's a [response ](https://paste.ofcode.org/cqNgRTqLFeeS8GCvuk2hgu)from my physical vivotek cc8160 camera)

How about the ONVIF device service endpoint as the unique identifier?
helm key: 
```
onvif.configuration.discoveryDetails.onvifUrls,action: filter action to take on a set of ONVIF URLs.
onvif.configuration.discoveryDetails.onvifUrls.items: ONVIF URLs that the filter action acts upon
```

> * I think we could explore a way to identify cameras without MAC address. I am not sure how common it is for IP cameras to use scopes.

--> Scopes can be retrieved from the WS-Discovery response. However, it might not be a common user scenario
to use scopes for a user. ONVIF device entry point might be an easy one.

> * I agree that finding a solution to get credentials to the Discovery Handler is probably the best solution and one we have been exploring. This PR takes a look at using a device registry with Akri [Implement external device inventory integration #520](https://github.com/project-akri/akri/pull/520)

--> That's an interesting one, thanks for the information here. Will definitely have a look at it!

**Comment by martin-weber** [comment]
@kate-goldenring : This is a really important feature as in most productive systems authentication has to be enable and without this feature Akri ONVIF cannot be used.

> We discussed this a little in our community meeting today. I think we need to get a unique identifier from the camera (without authentication) in order to have an identifier to pass to a registry to get credentials. Maybe we circle back to looking into how to use a tool like `arp` (or equivalent library) to get mac addresses

`arp` and mac-address might not work for use cases where the cameras are in a different subnet than Akri which is often the case with cluster network and camera network separation.
Agree with @markwu010 , the service endpoint would be a good option.

**Comment by kate-goldenring** [comment]
@markwu010 and @martin-weber using the service endpoint sounds fine to me. Are either of you interested in taking on this work.

The change would be to stop using the result of [`get_device_ip_and_mac_address`](https://github.com/project-akri/akri/blob/7d35269eeb31c0281533380e5cdfc82a279131e1/discovery-handlers/onvif/src/discovery_handler.rs#L157) when filtering as an identifier and instead use the service endpoints returned by `simple_onvif_discover`.

**Comment by johnsonshih** [comment]
According to [ONVIF core spec](https://www.onvif.org/specs/core/ONVIF-Core-Specification.pdf) sec 7.3.1,  The combination of an wsadis:Address
and wsadis:ReferenceProperties provide a stable and globally-unique identifier.
We can use "wsadis:Address + wsadis:ReferenceProperties.Address" as the identifier of an Onvif device.

7.3.1 Endpoint reference
A device or an endpoint that takes the client role should use a URN:UUID [RFC4122] as the address property
of its endpoint reference.
The device or an endpoint that takes the client role shall use a stable, globally unique identifier that is constant
across network interfaces as part of its endpoint reference property. The combination of an wsadis:Address
and wsadis:ReferenceProperties provide a stable and globally-unique identifier.

**Comment by johnsonshih** [comment]
For IP and Mac address filters, we can keep them but the DH can be flexible to skip querying ip/mac address from Onvif devices if neither of them are used (set to Exclude None).  The consequence of not using the ip/mac address filters is Onvif DH won't expose the environment variables: ONVIF_DEVICE_IP_ADDRESS and ONVIF_DEVICE_MAC_ADDRESS_LABEL_ID to brokers.

**Comment by agracey** [comment]
Just to make sure, these two still allow for the workload (broker) to find the device on the network, right?

**Comment by johnsonshih** [comment]
Currently the sample broker only uses ONVIF_DEVICE_SERVICE_URL to reach to the device.  ONVIF_DEVICE_IP_ADDRESS and ONVIF_DEVICE_MAC_ADDRESS are not used.  so there is no impact to the sample broker.  but if a workload does rely on the IP and MAC address and, in the future, we change the Onvif DH to only expose ONVIF_DEVICE_IP_ADDRESS and ONVIF_DEVICE_MAC_ADDRESS when possible, it might be an issue for those brokers that rely on IP/MAC address but that can be solved by providing credentials to perform authenticated discovery (PR in review https://github.com/project-akri/akri/pull/619)
