### ISSUE TITLE
Simplify and optimize builds (Makefiles and Workflows)

### ISSUE THREAD

**Issue by bfjelds** [project-akri/akri#253]
The Akri builds are based on Makefile.  The Makefile can be run locally and are run from our Workflows.  They work.  And that might be the best thing that can be said about them.

But they are hard to maintain and easy to get incorrect and have no linting/validation.

This is a pattern that is all over the scripts that seems ridiculous (there must be a better way, a more function-like way with some reuse):

```
ifeq (1, ${BUILD_ARM32})
	docker build $(CACHE_OPTION) -f $(DOCKERFILE_DIR)/Dockerfile.controller . -t $(PREFIX)/controller:$(LABEL_PREFIX)-$(ARM32V7_SUFFIX) --build-arg PLATFORM=$(ARM32V7_SUFFIX) --build-arg CROSS_BUILD_TARGET=$(ARM32V7_TARGET)
endif
```

The automated Workflow builds are based on the Makefiles.  For each Rust container, we build the entire source tree for a given platform, then put the appropriate binary into the appropriate container (so, we build the whole tree to grab the agent, the whole tree to grab the controller, etc).  It would be better to only build once if possible.

**Comment by bfjelds** [comment]
Also, at a minimum, we should provide much more documentation around how the existing system works.

**Comment by kate-goldenring** [comment]
@bfjelds can this PR be closed due to https://github.com/deislabs/akri/pull/270 which makes it so we only build our rust components once in our Workflows?

**Comment by bfjelds** [comment]
I think #270 is only part of this issue ... part of this issue was intended to address the fact that the Makefiles were created by someone who doesn't know make (me).  There must be better ways to create the Makefiles that are more manageable and clear.

**Comment by kate-goldenring** [comment]
That **Makes** sense. We can see this issue as a call for help for optimizing our makefiles
