### ISSUE TITLE
Test K3s, Kubernetes, and MicroK8s workflow periodically failing

### ISSUE THREAD

**Issue by kate-goldenring** [project-akri/akri#322]
**Describe the bug**
Akri's workflow to test Akri on K3s, Kubernetes, and MicroK8s periodically fails due to GitHub Runners running out of compute resources and the kubelet evicting Pods. The failure rate has been reduced by using release builds in PRs (https://github.com/deislabs/akri/pull/301), reducing the size of Debug Echo brokers by using `nginx:stable-alpine` (https://github.com/deislabs/akri/pull/301), reducing compute resource eviction limits in the MicroK8s kubelet (https://github.com/deislabs/akri/pull/301) and the K3s kubelet (https://github.com/deislabs/akri/pull/313). 

Also, tests are being done with unshared debug echo devices to reduce the length of time the tests run by 5 minutes (shared devices get a 5 min offline grace period) and therefore the chance of failure. This should be changed back to using shared once the failures are resolved as it is the more complex scenario.

**Potential solution**
Akri should host its own workflow runners that have more disk and RAM.

GitHub runners have the following [hardware specifications for Linux virtual machines](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources):
2-core CPU
7 GB of RAM memory
14 GB of SSD disk space

However, [MicroK8's documentation](https://microk8s.io/docs) states that "At least 20G of disk space and 4G of memory are recommended."

**Comment by bfjelds** [comment]
Workaround: rerunning job typically resolves the problem
