### ISSUE TITLE
Execute workloads based on labels instead of flags in PR titles

### ISSUE THREAD

**Issue by kate-goldenring** [project-akri/akri#334]
Currently, certain workflows are being skipped/executed [based on flags set in PR titles](https://github.com/deislabs/akri/blob/v0.6.5/docs/contributing.md#pr-title-flags). For example, adding `[SAME VERSION]` to a PR title prevents the version check workflow from running. However, after adding a flag to a title, checks cannot simply be re-run, since they refer to the state of the PR of the last commit. Resultingly, another commit must be pushed to the PR in order for checks to properly register the PR title change (and therefore flag). Running workflows based on labels instead of flags may remove this issue of pushing new commits.

Work to be done:
1. Confirm whether actions can reference newly added labels without new commits needing to be pushed. (Even if this isnt the case, labels are still cleaner than PR title flags)
2. In the [opencv base build](https://github.com/deislabs/akri/blob/main/.github/workflows/build-opencv-base-container.yml), [rust base build](https://github.com/deislabs/akri/blob/main/.github/workflows/build-rust-crossbuild-container.yml), and [version check](https://github.com/deislabs/akri/blob/main/.github/workflows/check-versioning.yml) workflows, `github.event.pull_request.title` should be changed to `github.event.label.name` and point to newly made labels (possibly `same version`,  `allow intermediate builds`, and `ignore intermediate builds`).
3. Update [PR template](https://github.com/deislabs/akri/blob/main/.github/pull_request_template.md) and [contributing doc](https://github.com/deislabs/akri/blob/main/docs/contributing.md#pr-title-flags) to explain this new model

**Comment by vincepnguyen** [comment]
I will investigate this issue
