### ISSUE TITLE
Cluster setup flow for microk8s points to 1.19

### ISSUE THREAD

**Issue by jiria** [project-akri/akri#352]
**Is your feature request related to a way you would like Akri extended? Please describe.**
Currently, the [cluster setup page](https://github.com/deislabs/akri/blob/main/docs/setting-up-cluster.md#option-2-set-up-a-microk8s-cluster) points to 1.19 version of Kubernetes when setting up MicroK8s. 

**Describe the solution you'd like**
Could we remove the channel and let users deploy the latest version? That is currently 1.21.1.

**Comment by kate-goldenring** [comment]
I believe we chose a specific version so it could be one that we are validating in our tests. Maybe we have this be a part of our release cycle to have the docs point to the latest K8s version we are testing. Or we could use the latest stable channel and if there are any issues, it will help us catch them sooner.

**Comment by kate-goldenring** [comment]
@jiria Maybe we change it to latest but add a note pointing to the current versions we test?

**Comment by bfjelds** [comment]
maybe another solution would be to have the docs **not** call out a specific version, but rather link to our supported versions (in the CHANGELOG.md maybe?)
