### ISSUE TITLE
Use `tokio::sync::RwLock` instead of `tokio::sync::Mutex`

### ISSUE THREAD

**Issue by kate-goldenring** [project-akri/akri#376]
**Is your feature request related to a problem? Please describe.**
Throughout Akri's code, we are often using a `Mutex` where a [`RwLock`](https://docs.rs/tokio/1.11.0/tokio/sync/struct.RwLock.html) would be preferred, as it provides multiple read handles while only one write handle. For example, our maps of data, such as the Agent's `InstanceMap` which is `Arc<Mutex<HashMap<String, InstanceInfo>>>` would be better designed as `Arc<RwLock<HashMap<String, InstanceInfo>>>` as many times only reads are needed.

**Describe the solution you'd like**
Change usage of `Mutex` to `RwLock` where preferable.

**Comment by harrison-tin** [comment]
I'm interested in working on this!
