### ISSUE TITLE
`ListAndWatch` should only send `Devices` when the list has changed

### ISSUE THREAD

**Issue by kate-goldenring** [project-akri/akri#379]
**Is your feature request related to a problem? Please describe.**
Akri makes a device plugin for each device it discovers, so kubelet can advertise it as a node-level resource. Currently, the Agent in `device_plugin_service.rs` in its implementation of `list_and_watch` has each device plugin send the list of devices on a loop with interval of `LIST_AND_WATCH_SLEEP_SECS`. An additional step should be added before sending the devices to the kubelet [here](https://github.com/deislabs/akri/blob/main/agent/src/util/device_plugin_service.rs#L187) that checks if the [devices](https://github.com/deislabs/akri/blob/main/agent/src/util/device_plugin_service.rs#L183) have changed from the previous list of devices. The device plugin manager (implemented by kubelet) assumes -- see [code commented description of ListAndWatch](https://kubernetes.io/docs/concepts/extend-kubernetes/compute-storage-net/device-plugins/#device-plugin-implementation) -- that it will only receive updates when state has changed. We are currently not following that paradigm. 

**A potential solution**
Keep a `Vector` of the previously returned devices and compare it to the ones to be sent. `Device` implements `PartialEq` so a `==` comparison can be made. If there are no changes, then do not send the devices that loop iteration.

**Comment by harrison-tin** [comment]
I'm interested in working on this!
