### ISSUE TITLE
Fix `cargo clippy` warnings

### ISSUE THREAD

**Issue by kate-goldenring** [project-akri/akri#383]
[`cargo clippy`](https://github.com/rust-lang/rust-clippy) is a linter that suggest Rust code improvements. We currently check all PRs for clippy errors before merging in our [Check Rust workflow](https://github.com/deislabs/akri/blob/4ad5743182e9d3af53828a298ccbe0e05810585c/.github/workflows/check-rust.yml#L48); however, this does not seem to prevent merging code that adds more clippy warnings.

All clippy warnings should be addressed:
`cargo clippy --all`

Furthermore, clippy errors in tests should be addressed
`cargo clippy --all-targets --all-features -- -D warnings`

Some of these may be able to be addressed via `cargo clippy --fix`

Also, our [Check Rust workflow](https://github.com/deislabs/akri/blob/4ad5743182e9d3af53828a298ccbe0e05810585c/.github/workflows/check-rust.yml) could be updated to run `cargo clippy --all-targets --all-features -- -D warnings` instead of `cargo clippy --all` so as to always check test code and disallow merging code that creates clippy warnings

**Comment by Saran51** [comment]
I will work on this as part of OSD contribution.

**Comment by kate-goldenring** [comment]
Addressing the `function has too many arguments` warnings may require creating new structures in the code and could be skipped. For example:
```
warning: this function has too many arguments (10/7)
   --> controller/src/util/pod_watcher.rs:478:5
    |
478 | /     async fn create_or_update_service(
479 | |         &self,
480 | |         instance_name: &str,
481 | |         configuration_name: &str,
...   |
488 | |         kube_interface: &impl KubeInterface,
489 | |     ) -> anyhow::Result<()> {
```

**Comment by kate-goldenring** [comment]
@Saran51 any updates on your progress with this?

**Comment by Ragnyll** [comment]
Hey, its been a few months since there's been any commit by the assignee on this issue. I've raised a PR that answers this issue and is up to date. If that is inappropriate feel free to close, but I think it should help. #442
