### ISSUE TITLE
NodeSelector for Agent in Helm

### ISSUE THREAD

**Issue by kferrone** [project-akri/akri#414]
**Is your feature request related to a problem? Please describe.**
Not all of my nodes need the agent on it. By default every node gets the agent on it. 

**Is your feature request related to a way you would like Akri extended? Please describe.**
I would like to select only the nodes which have the devices that the Akri agent will actually use. 

**Describe the solution you'd like**
Simply add `nodeSelector` to the agent section in the helm `values.yaml`. Then apply them to the `nodeSelector` in the template. 

**Describe alternatives you've considered**
I can patch the chart in the after render handler but it's not ideal.

**Comment by kate-goldenring** [comment]
This sounds like a good add to me. I am assuming this also would pertain to discovery handlers as well.  @kferrone would you be interested in putting in a PR witht he modified charts?

**Comment by kferrone** [comment]
Sure. Wouldn't be too hard.

**Comment by kferrone** [comment]
Sorry, I've been pretty busy with work. New job chaos ya know. I will have some time this week to work on this again.

**Comment by kate-goldenring** [comment]
> Sorry, I've been pretty busy with work. New job chaos ya know. I will have some time this week to work on this again.

@kferrone thanks for the update!
