### ISSUE TITLE
agent pods keep failing and throw thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()`

### ISSUE THREAD

**Issue by OsamaEnergia** [project-akri/akri#446]
Hi,
I got the following error in akri agent pods, if you could please help with it.

**Describe the bug**
- most of the agent pods keep restarting, logs as below
- this leads to a problem with some of the broker pods cannot be terminated using the discovery handler as it will connect to a new agent on this node
- I enabled RUST_BACKTRACE=full in agent daemonset  to get below logs

**Kubernetes Version: [Azure Kubernetes version : 1.21.2]**

**Logs**
[2022-02-18T15:40:00Z TRACE agent::util::slot_reconciliation] periodic_slot_reconciliation - iteration end
[2022-02-18T15:40:00Z TRACE agent::util::slot_reconciliation] periodic_slot_reconciliation - iteration pre sleep
[2022-02-18T15:40:10Z TRACE agent::util::slot_reconciliation] periodic_slot_reconciliation - iteration call reconiler.reconcile
[2022-02-18T15:40:10Z TRACE agent::util::slot_reconciliation] reconcile - thread iteration start [Mutex { data: {}, poisoned: false, .. }]
[2022-02-18T15:40:10Z TRACE agent::util::slot_reconciliation] get_node_slots - Command failed to call crictl: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }
[2022-02-18T15:40:10Z TRACE agent::util::slot_reconciliation] reconcile - get_node_slots failed: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }
[2022-02-18T15:40:10Z TRACE agent::util::slot_reconciliation] periodic_slot_reconciliation - iteration end
[2022-02-18T15:40:10Z TRACE agent::util::slot_reconciliation] periodic_slot_reconciliation - iteration pre sleep
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: WatchFailed { source: ReadEvents(Custom { kind: Other, error: hyper::Error(Body, hyper::Error(Body, Os { code: 104, kind: ConnectionReset, message: "Connection reset by peer" })) }), backtrace: Backtrace(()) }', agent/src/util/config_action.rs:82:10
stack backtrace:
   0:     0x55b113376e40 - std::backtrace_rs::backtrace::libunwind::trace::ha0ad43e8a952bfe7
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:     0x55b113376e40 - std::backtrace_rs::backtrace::trace_unsynchronized::h6830419c0c4130dc
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x55b113376e40 - std::sys_common::backtrace::_print_fmt::h8f3516631ffa1ef5
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x55b113376e40 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::he1640d5f0d93f618
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x55b11339d46c - core::fmt::write::h88012e1f01caeebf
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/fmt/mod.rs:1115:17
   5:     0x55b1133706f5 - std::io::Write::write_fmt::h360fa85b30182555
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/io/mod.rs:1665:15
   6:     0x55b113378f7b - std::sys_common::backtrace::_print::ha1f00492f406a015
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x55b113378f7b - std::sys_common::backtrace::print::hd54561b13feb6af3
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x55b113378f7b - std::panicking::default_hook::{{closure}}::h84fe124cd0864662
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:208:50
   9:     0x55b113378a51 - std::panicking::default_hook::h5a8e74a76ce290a7
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:225:9
  10:     0x55b113379644 - std::panicking::rust_panic_with_hook::h67c812a4fe9d4c91
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:622:17
  11:     0x55b113379127 - std::panicking::begin_panic_handler::{{closure}}::h33f9c1b96af300d7
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:519:13
  12:     0x55b11337733c - std::sys_common::backtrace::__rust_end_short_backtrace::h51bae64be5921f0e
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/sys_common/backtrace.rs:141:18
  13:     0x55b113379089 - rust_begin_unwind
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:515:5
  14:     0x55b112923d71 - core::panicking::panic_fmt::h12a3a3c256485fca
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/panicking.rs:92:14
  15:     0x55b112923e63 - core::result::unwrap_failed::h2d8d0952e3250de9
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/result.rs:1599:5
  16:     0x55b1129b5b6b - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h0cc2b6c498bcacd4
  17:     0x55b112c90333 - tokio::runtime::task::harness::poll_future::hd6faa3b9a78f132d
  18:     0x55b112ca3ef7 - tokio::runtime::task::harness::Harness<T,S>::poll::h6cc48a4815a7c86e
  19:     0x55b11333771c - tokio::runtime::thread_pool::worker::Context::run_task::hdd8b3dc4e17dadaa
  20:     0x55b113336793 - tokio::runtime::thread_pool::worker::Context::run::hb9a3dd9f8b66942d
  21:     0x55b113321b13 - tokio::macros::scoped_tls::ScopedKey<T>::set::h291cdd91e0f4c1d4
  22:     0x55b113335f21 - tokio::runtime::thread_pool::worker::run::h32449cbe24a1e67d
  23:     0x55b1133223e1 - tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut::h782588b09d34e677
  24:     0x55b11332dc70 - tokio::runtime::task::harness::Harness<T,S>::poll::hc69054c66e4eda7c
  25:     0x55b11332b739 - tokio::runtime::blocking::pool::Inner::run::h9348c97e7d136698
  26:     0x55b11332445b - std::sys_common::backtrace::__rust_begin_short_backtrace::h2c2bcf23d7c643fd
  27:     0x55b11333fbd8 - core::ops::function::FnOnce::call_once{{vtable.shim}}::hacdd656da0b85665
  28:     0x55b11337f627 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h6bff7798948b1075
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/alloc/src/boxed.rs:1572:9
  29:     0x55b11337f627 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hc2d25ac38f6b2342
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/alloc/src/boxed.rs:1572:9
  30:     0x55b11337f627 - std::sys::unix::thread::Thread::new::thread_start::hbba5bc368baac205
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/sys/unix/thread.rs:74:17
  31:     0x7f078cbb4fa3 - start_thread
  32:     0x7f078c95d4cf - clone
  33:                0x0 - <unknown>
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: JoinError::Panic(...)', agent/src/main.rs:88:14
stack backtrace:
   0:     0x55b113376e40 - std::backtrace_rs::backtrace::libunwind::trace::ha0ad43e8a952bfe7
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:     0x55b113376e40 - std::backtrace_rs::backtrace::trace_unsynchronized::h6830419c0c4130dc
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x55b113376e40 - std::sys_common::backtrace::_print_fmt::h8f3516631ffa1ef5
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x55b113376e40 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::he1640d5f0d93f618
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x55b11339d46c - core::fmt::write::h88012e1f01caeebf
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/fmt/mod.rs:1115:17
   5:     0x55b1133706f5 - std::io::Write::write_fmt::h360fa85b30182555
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/io/mod.rs:1665:15
   6:     0x55b113378f7b - std::sys_common::backtrace::_print::ha1f00492f406a015
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x55b113378f7b - std::sys_common::backtrace::print::hd54561b13feb6af3
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x55b113378f7b - std::panicking::default_hook::{{closure}}::h84fe124cd0864662
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:208:50
   9:     0x55b113378a51 - std::panicking::default_hook::h5a8e74a76ce290a7
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:225:9
  10:     0x55b113379644 - std::panicking::rust_panic_with_hook::h67c812a4fe9d4c91
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:622:17
  11:     0x55b113379127 - std::panicking::begin_panic_handler::{{closure}}::h33f9c1b96af300d7
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:519:13
  12:     0x55b11337733c - std::sys_common::backtrace::__rust_end_short_backtrace::h51bae64be5921f0e
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/sys_common/backtrace.rs:141:18
  13:     0x55b113379089 - rust_begin_unwind
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:515:5
  14:     0x55b112923d71 - core::panicking::panic_fmt::h12a3a3c256485fca
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/panicking.rs:92:14
  15:     0x55b112923e63 - core::result::unwrap_failed::h2d8d0952e3250de9
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/result.rs:1599:5
  16:     0x55b1129f9786 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::hfd01ea98d8ae7599
  17:     0x55b112c8f613 - tokio::runtime::task::harness::poll_future::h93c64df0b9444e09
  18:     0x55b112ca38b4 - tokio::runtime::task::harness::Harness<T,S>::poll::h67f80cd1d47933cd
  19:     0x55b113337820 - tokio::runtime::thread_pool::worker::Context::run_task::hdd8b3dc4e17dadaa
  20:     0x55b113336793 - tokio::runtime::thread_pool::worker::Context::run::hb9a3dd9f8b66942d
  21:     0x55b113321b13 - tokio::macros::scoped_tls::ScopedKey<T>::set::h291cdd91e0f4c1d4
  22:     0x55b113335f21 - tokio::runtime::thread_pool::worker::run::h32449cbe24a1e67d
  23:     0x55b1133223e1 - tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut::h782588b09d34e677
  24:     0x55b11332dc70 - tokio::runtime::task::harness::Harness<T,S>::poll::hc69054c66e4eda7c
  25:     0x55b11332b739 - tokio::runtime::blocking::pool::Inner::run::h9348c97e7d136698
  26:     0x55b11332445b - std::sys_common::backtrace::__rust_begin_short_backtrace::h2c2bcf23d7c643fd
  27:     0x55b11333fbd8 - core::ops::function::FnOnce::call_once{{vtable.shim}}::hacdd656da0b85665
  28:     0x55b11337f627 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h6bff7798948b1075
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/alloc/src/boxed.rs:1572:9
  29:     0x55b11337f627 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hc2d25ac38f6b2342
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/alloc/src/boxed.rs:1572:9
  30:     0x55b11337f627 - std::sys::unix::thread::Thread::new::thread_start::hbba5bc368baac205
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/sys/unix/thread.rs:74:17
  31:     0x7f078cbb4fa3 - start_thread
  32:     0x7f078c95d4cf - clone
  33:                0x0 - <unknown>
Error: JoinError::Panic(...)

**Comment by kate-goldenring** [comment]
Hi @OsamaEnergia, can you provide some more background on what type of cluster and nodes you are using? It looks like the Agent is losing its connection to the API server when watching `Configuration` resources. Also, as a side note, you should enable `crictl` (avoiding these errors `Command failed to call crictl`). We are in the middle of a release, so our documentation is a little off. So, if you are using the release chart `helm install akri akri-helm-charts/akri` then [see these instructions](https://github.com/project-akri/akri-docs/blob/v0.7.0/docs/user-guide/cluster-setup.md#configure-crictl). If using the development chart (`helm install akri akri-helm-charts/akri-dev`), these are the correct [configure `crictl` instructions](https://docs.akri.sh/user-guide/cluster-setup#configure-crictl)

**Comment by romoh** [comment]
Hi @OsamaEnergia, 
AKS uses containerd and not dockerShim, so you need to update `AKRI_HELM_CRICTL_CONFIGURATION` before installing akri.

The following steps work on a 2 node AKS cluster using K8s 1.21.9:

```
helm repo add akri-helm-charts https://project-akri.github.io/akri/ 

export AKRI_HELM_CRICTL_CONFIGURATION="--set agent.host.containerRuntimeSocket=/run/containerd/containerd.sock"

helm install akri akri-helm-charts/akri-dev  \
    $AKRI_HELM_CRICTL_CONFIGURATION  \
    --set agent.allowDebugEcho=true  \
    --set debugEcho.discovery.enabled=true  \
    --set debugEcho.configuration.enabled=true  \
    --set debugEcho.configuration.brokerPod.image.repository=nginx  \
    --set debugEcho.configuration.brokerPod.image.tag=stable-alpine  \
    --set debugEcho.configuration.shared=false 
```

what version of akri are you using? the steps may be slightly different if you are using an older version.

**Comment by OsamaEnergia** [comment]
@kate-goldenring  , @romoh  Thank you for your reply!

I'm using:
- AKS cluster with 8 nodes where Kubernetes version: 1.21.2 and Container runtime version: containerd://1.4.9+azure
- Deploying Akri release (using `helm upgrade --install --version 0.7.0 akri -f akri-values.yaml akri-helm-charts/akri`)
- akri-values.yaml used `agent:
  host:
    crictl: /usr/local/bin/crictl
    dockerShimSock: /run/containerd/containerd.sock
    allowDebugEcho: true` and other discovery handlers 

The problem happens usually with some of the agent pods not all (like 4 out of 8), and the controller pod (which is one pod by default) also restarts from time to time (less frequent).

I also tried the akri-dev with `--set agent.host.containerRuntimeSocket=/run/containerd/containerd.sock` and same issue occured.

- Is there any limitation on the number of nodes that could be used? 
- Is there a way to make agent pods stateless, so even if the agent restarted it will be able to take control of the broker pod that has been created before? as the big impact now that I get orphan broker pods that I cannot terminate using discovery handler if agent pod restarted

**Comment by kate-goldenring** [comment]
@OsamaEnergia, not sure why the connection reset is happening. However to this comment :

> Is there a way to make agent pods stateless, so even if the agent restarted it will be able to take control of the broker pod that has been created before? 

If `crictl` is properly configured, then the broker Pods should not be orphaned. I believe that the Agent will be able to determine that broker Pods are running and update the Instances to reflect that. Have you found the brokers being orphaned when you are properly configuring crictl?

**Comment by OsamaEnergia** [comment]
Thanks @kate-goldenring , you are right that with the right configuration of `crictl` the agent will handle broker pods.
the problem was in the discovery handler (I use custom discovery handler based on rust template), once the connection with agent dropped it was forgetting all discovered_devices_map, I had to use global static to move devices from one time to another.

still, the main issue of connection reset (inside "agent "and less frequent in "controller") happening tho.

**Comment by kate-goldenring** [comment]
@OsamaEnergia, good to know the agent is working as expected with regards to orphan pods.

It sounds like your discovery handler does not discover all devices in one `discover` call rather discovers a subset of devices that can be added to a stateful map it maintains. Making the map global or scoped outside of the `DiscoveryHandler` makes sense. Or maybe the disconnects with the Agent could be handled differently?

Agree that the error is still disconcerting. are the logs / where the error occurs the same in the controller and agent?

**Comment by kate-goldenring** [comment]
@OsamaEnergia to provide more context, it looks like this is the [`WatchFailed`](https://docs.rs/kube/latest/kube/runtime/watcher/enum.Error.html) is the error that is being thrown by the `kube_rs::watcher` which is instantiated on [this line](https://github.com/project-akri/akri/blob/v0.7.0/agent/src/util/config_action.rs#L99). Do you mind trying Akri version 0.6.5? Thats before we started using the watcher. I'll also look into this bug specifically on the watcher

**Comment by kate-goldenring** [comment]
this issue looks related: https://github.com/kube-rs/kube-rs/issues/567

**Comment by OsamaEnergia** [comment]
@kate-goldenring
about rbac, I disabled rbac and tried it with Akri 0.70 and 0.6.5 and the connection reset is still there.
"version-rs" is working fine and stable on the cluster.

please find 4 logs https://justpaste.it/3s9e6 (separated by --------------Akri) for:
- Akri Controller log (rbac.enabled=false, akri 0.7.0, full log file)
- Akri Agent log (rbac.enabled=false, akri 0.7.0, full log file)
- Akri Controller log (rbac.enabled=false, akri 0.6.5)
- Akri Agent log (rbac.enabled=false, akri 0.6.5)

**Comment by kate-goldenring** [comment]
@OsamaEnergia thanks for the logs. I wonder we can get more context on this by asking about [this note](https://github.com/kube-rs/kube-rs/blob/master/kube-client/src/client/mod.rs#L321) in the `kube-rs` implementation. We are getting a `WatchError(ReadError...))` which only is thrown at that line of their implementation

**Comment by kate-goldenring** [comment]
@OsamaEnergia, we updated to the latest kube-rs in https://github.com/project-akri/akri/pull/458. I'd be curious is your issue is resolved by pointing to the latest `akri-dev` chart
