### ISSUE TITLE
Consider using dedicated namespace for Akri by default

### ISSUE THREAD

**Issue by jiria** [project-akri/akri#448]
**Is your feature request related to a problem? Please describe.**
Following the instructions, Akri by default is deployed into the default namespace. Consider using dedicated namespace for Akri by default.

**Describe the solution you'd like**
Instructions for helm install could contain the desired target namespace to be used.

**Comment by kate-goldenring** [comment]
Hi @jiria this issue may better live in Akri's documentation repository: https://github.com/project-akri/akri-docs. Can you open this there and then we can link to it from here and close this one out?

**Comment by romoh** [comment]
That would be a documentation fix to include ` --create-namespace --namespace akri` to our helm install commands.

**Comment by kate-goldenring** [comment]
An example of how prometheus does this: https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack#redeploy-with-new-name-downtime
We'd need to add similar notes about presumed namespace usage
