### ISSUE TITLE
Update to latest Kubernetes client (`kube-rs`) and types (`k8s-openapi`) versions

### ISSUE THREAD

**Issue by kate-goldenring** [project-akri/akri#453]
Akri should be updated to use the latest versions of the Kubernetes client ([`kube-rs`](https://github.com/kube-rs/kube-rs)) and types (`k8s-openapi`) crates. The `k8s-openapi` version is dependent on the `kube-rs` version as seen in the [`kube-rs` README](https://github.com/kube-rs/kube-rs).

**Comment by Ragnyll** [comment]
Ay, mind if I take this issue? Id like to take a crack at this as I'm familiarizing myself with the project more

**Comment by kate-goldenring** [comment]
> Ay, mind if I take this issue? Id like to take a crack at this as I'm familiarizing myself with the project more

Hey @Ragnyll that would be great! I just assigned you to it. Let me know if you run into any issues.

**Comment by Ragnyll** [comment]
Opened https://github.com/project-akri/akri/pull/458#issue-1160890021
