### ISSUE TITLE
Switch to using `containerd` as default container runtime socket for standard Kubernetes

### ISSUE THREAD

**Issue by kate-goldenring** [project-akri/akri#455]
**Current state**
Currently if a user specifies they are using standard Kuberntes (`--set kubernetesDistro=K8s`), then [Akri assumes](https://github.com/project-akri/akri/blob/main/deployment/helm/values.yaml#L104) the container runtime socket to be at `/var/run/dockershim.sock`. This should be changed to `/run/containerd/containerd.sock` as Docker as the underlying runtime in K8s [has been deprecated](https://kubernetes.io/blog/2020/12/02/dont-panic-kubernetes-and-docker/) in favor of CRI runtimes like containerd.

**Describe the solution you'd like**
Update the defaults in the helm templates [like in the Agent template here](https://github.com/project-akri/akri/blob/main/deployment/helm/templates/agent.yaml#L113), update [end to end test pipeline](https://github.com/project-akri/akri/blob/main/.github/workflows/run-test-cases.yml#L214) to ensure that K8s installation has been updated to use containerd, and update the Akri [cluster setup documentation](https://github.com/project-akri/akri-docs/blob/main/docs/user-guide/cluster-setup.md).

**Comment by Rishit-dagli** [comment]
@kate-goldenring I would love to take this up

**Comment by kate-goldenring** [comment]
Awesome @Rishit-dagli! Just assigned it to you. With this may come some thoughts into removing support for testing older versions of K8s, so if you run into configuration roadblocks around K8s v1.16-1.18, it might be worth removing them from the matrix
