### ISSUE TITLE
Specify rustc version in Cargo.toml files

### ISSUE THREAD

**Issue by Ragnyll** [project-akri/akri#470]
As of rust 1.56 the [`rust-version`](https://doc.rust-lang.org/cargo/reference/manifest.html#the-rust-version-field) field is stabilized and I believe this should be included in Akri's cargo.toml files. 

When building locally this just helps specify the minimum version of rust expected, which should be the version specified by the [CI](https://github.com/project-akri/akri/blob/main/.github/workflows/check-rust.yml#L36). 

This is a minuscule change, but it is nice when trying to reproduce bug reports.

**Comment by Ragnyll** [comment]
I wanted to throw this out for discussion real quick because of what the docs say: 
> Setting the rust-version key in [package] will affect all targets/crates in the package, including test suites, benchmarks, binaries, examples, etc.

Otherwise I'd think this would be a very easy issue to knock out real quick.

**Comment by kate-goldenring** [comment]
This is a great idea for creating a more consistent dev experience. Would you willing to add it in?

**Comment by Ragnyll** [comment]
opened PR https://github.com/project-akri/akri/pull/472
