### ISSUE TITLE
Exception in Monitoring Broker

### ISSUE THREAD

**Issue by hemantkathuria** [project-akri/akri#473]
I am following the sample given [Here](https://docs.akri.sh/demos/opc-thermometer-demo)

I have found 2 issues.

1) Even if I choose to go without certificates, monitoring broker fails to load as it is expecting a path to be mounted "/etc/opcua-certs/client-pki".

2) After doing the certificate registration and mounting the same, the broker fails at below. Since only exception message is logged, it is difficult to find the root cause.
```
.NET Core OPC UA Console Client Start
1 - Create an Application Configuration.
Client is using a certificate with subject CN=AkriBroker
2 - Discover endpoints of opc.tcp://10.0.0.4:62541/Quickstarts/ReferenceServer.
←[40m←[32minfo←[39m←[22m←[49m: Microsoft.Hosting.Lifetime[0]
      Now listening on: http://[::]:8083
←[40m←[32minfo←[39m←[22m←[49m: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
←[40m←[32minfo←[39m←[22m←[49m: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Production
←[40m←[32minfo←[39m←[22m←[49m: Microsoft.Hosting.Lifetime[0]
      Content root path: /app
    Selected endpoint uses: Aes256_Sha256_RsaPss
3 - Create a session with OPC UA server.
4 - Browse the OPC UA server namespace.
Exception: One or more errors occurred. (BadUnexpectedError)
←[40m←[32minfo←[39m←[22m←[49m: Microsoft.Hosting.Lifetime[0]
      Application is shutting down...

```

**Comment by kate-goldenring** [comment]
Hi @hemantkathuria, the sample broker tries to find certificates and throws and catches the error if none are found. When you didn't use certificates, did you see the following log: `Exception {0} thrown when trying to use application certificate mounted at {1}. Using no security.`? The logging of the error and then continuation is misleading and maybe should be changed. 
I am looking into reproing your second error -- thanks for pointing this out!

**Comment by kate-goldenring** [comment]
@hemantkathuria when creating the opc ua servers, did you check out a specific tag of [the .NET opc ua library](https://github.com/OPCFoundation/UA-.NETStandard). We have another issue up https://github.com/project-akri/akri/issues/464 to update this sample because main has progressed beyond the writeup.

**Comment by kate-goldenring** [comment]
@hemantkathuria I was able to walk through the demo successfully -- i did have the advantage of knowing the commit of the .NET servers at which the demo was originally created :) I put in a PR to update the demo to queue for pulling the appropriate tag of the .NET Server repos. Does using this version of the servers resolve your issue?

**Comment by kate-goldenring** [comment]
@hemantkathuria do you think this is resolved and ready to close or should be kept open as an issue on improving error logging in the broker?
