### ISSUE TITLE
Enable udev discovery handler to discover multiple node devices

### ISSUE THREAD

**Issue by kate-goldenring** [project-akri/akri#490]
## Background
Akri's `udev` discovery handler assumes that each `udev` device consists of one devnode, so it reports each devnode captured by the provided udev rules as a separte device to Akri. 

However, many devices span multiple devnodes. For example, some USB cameras consist of several nodes, such as `/dev/video0` and `/dev/video1` where one contains metadata and the other does actual footage capturing. In this case, one camera should be reported rather than 2. The work around in this scenario, was to specificy only discovering cameras with `:capture:` capabilities ref https://github.com/project-akri/akri-docs/pull/36, but not all devices have a "dominant" node like this.

This issue was also inspired by the following question [from this slack thread](https://kubernetes.slack.com/archives/C01D9L7QE8Z/p1655309513284689): _I have a client who has devices they'd like to broker with Akri but their devices apparently function with multiple udev mounts. I have not dug too deeply into this use case yet, but they say this prevents the use of Akri. I guess my question is, can I use Akri with multiple udev mounts per broker?

## Potential solution
Additional discoveryDetails should be passed to the `udev` Discovery Handler that enable specifying a set or a common property shared among the devnodes associated with a device. 
Investigation needs to be done on whether common properties (such as vendor id) exist.

Pertinent code
- udev Discovery Handler [`discoveryDetails`](https://github.com/project-akri/akri/blob/2b42eb28a41aaab966eb2823a693464153a127ee/discovery-handlers/udev/src/discovery_handler.rs#L25) should be expanded to include ability to specify a "set" of nodes. This is then specified by the user in an Akri Configuration.
- udev Discovery Handler would set multiple devnode mounts [here](https://github.com/project-akri/akri/blob/2b42eb28a41aaab966eb2823a693464153a127ee/discovery-handlers/udev/src/discovery_handler.rs#L94)

**Comment by agracey** [comment]
Another use case for this would be POS systems that have a barcode scanner, receipt printer, touchpad, etc... Being able to discover the combined set and manage it as a single Instance could be useful!

**Comment by kate-goldenring** [comment]
@agracey in this case, do all of those devices have some udev property in common? We need some common udev filter we can apply to exclusively group these devices. that filter could be added as a discovery property of the Akri Configuration.

**Comment by agracey** [comment]
Not necessarily, they could be different discrete hardware with their own kernel subsystems. 

This could be solved in it's own discovery handler so there's no real functionality gap. This issue came up on the community call reminding me of the additional use-case so I figured it was worth mentioning here.

**Comment by diconico07** [comment]
Another way to group would be if the matched nodes are part of the same tree.
There would be a need for a grouping stage in the discovery handler, but it can work like this, for each matching node:

 1. Check if we have one of its parent in the matched table
 2. If yes then add the node to the mount list for it and continue with next one
 3. If no then add the node to the matched table
 4. Check if we have one of its children in the matched table
 5. If yes add all its mounts to the mount list of our node and delete the children entry in matched table

This feels better to me than hoping there will be a common property among the node of the same device without matching another similar unrelated device (there is usually ID_PATH for the video0/video1 case, but in the case you want to handle a keyboard/touchpad combo it won't work, well at least not with mine).

I'll try to do a PR for this to see if this is realistic.

The use case raised by @agracey looks more like grouping multiple independent devices and I'd rather see it solved at the controller level, an idea would be to have a way to instantiate a workload when a node have all needed devices kind (and amount) available. So if I have a `Configuration` for barcode scanners and one for receipt printers, I can have a resource that will trigger a workload if a node have both available (kind of a generalization of the broker workload in the `Configuration` where you can link to multiple `Configuration` resources that don't trigger a workload by themselves). But anyway I think it needs its own issue.

**Comment by kate-goldenring** [comment]
@diconico07 this sounds like a good approach to me; though i will say i am not fully familiar which the specification of how udev parents and children must be related. It would be nice to see if there is a specification out there that delineates that there is a device relation. Regardless, I think we should have a parameter to enable this so it is an optional feature for backwards compat.

To your second point about grouping different devices, I agree. In the past, we have called this desired feature ["resource grouping"](https://github.com/project-akri/akri-docs/blob/main/proposals/broker-deployment-strategies.md#resource-grouping) and do see it being done by the controller.

**Comment by diconico07** [comment]
Well udev parent and children must be related in a sysfs way, but there is no standard way of defining a peripheral boundaries unfortunately. I've seen many configurations here depending on the vendors and buses, most commonly for usb devices the topmost node (and its downstream) share the ID_SERIAL environment. For PCI devices it really depends on the vendors so nothing stable here.

I created a draft PR that implements this "recursive" grouping, I will get it out of draft when I finish writing its pair PR in docs.
