### ISSUE TITLE
Add support for adding container port in OpcUa broker pod

### ISSUE THREAD

**Issue by hemantkathuria** [project-akri/akri#493]
We plan to host an Asp.Net core API inside the OPCUA broker. It will be exposed on 5000 port.

Current Helm chart does not allow adding the below under PodSpec.

        brokerPod:
          ports:
          - containerPort: 5000
          - 
Please help in getting this added as this is a blocker for us.

**Comment by hemantkathuria** [comment]
Can we expect this change sometime soon? :) We are in urgent need of this. Please help :)

**Comment by leolumicrosoft** [comment]
I actually do not understand this request. There is already instance level service for each broker pod, and also a configuration level service for all broker pods created by a single configuration. You can define targetports for both instance level and configuration level service. That is enough for accessing your broker's API.

From Kubernetes document, containerport is just informational, please check the below quote from Kubernetes official website:

ports ([]ContainerPort)

Patch strategy: merge on key containerPort

Map: unique values on keys containerPort, protocol will be kept during a merge

List of ports to expose from the container. Exposing a port here gives the system additional information about the network connections a container uses, **but is primarily informational**. Not specifying a port here DOES NOT prevent that port from being exposed.

**Comment by Sonali-Rajput** [comment]
Where should I start with this issue?

**Comment by hemantkathuria** [comment]
> I actually do not understand this request. There is already instance level service for each broker pod, and also a configuration level service for all broker pods created by a single configuration. You can define targetports for both instance level and configuration level service. That is enough for accessing your broker's API.
> 
> From Kubernetes document, containerport is just informational, please check the below quote from Kubernetes official website:
> 
> ports ([]ContainerPort)
> 
> Patch strategy: merge on key containerPort
> 
> Map: unique values on keys containerPort, protocol will be kept during a merge
> 
> List of ports to expose from the container. Exposing a port here gives the system additional information about the network connections a container uses, **but is primarily informational**. Not specifying a port here **DOES NOT** prevent that port from being exposed.

Yes, you are right. When I opened the issue, I was unaware that it is informational, and it will work without adding the container port. So, we were actually able to move further as it worked without adding the container port. So, I would say, priority can be reduced further unless we want to allow the users to add information of ports also and this is how generally use and not sure how many are aware that it's informational only! :) Thank you
