### ISSUE TITLE
usb camera end to end demo issue

### ISSUE THREAD

**Issue by leolumicrosoft** [project-akri/akri#494]
Hi, I found this issue when I follow https://docs.akri.sh/demos/usb-camera-demo. I setup with an Azure virtual machine with Linux (ubuntu 20.0). The two virtual USB cameras created have ID_V4L_CAPABILITIES different from :capture:, which makes Akri unable to discover the virtual cameras and create broker pod. I simply change udev.configuration.discoveryDetails.udevRules[0]='KERNEL=="video[0-9]*"' so the demo works. But please check. This assumption may not be correct:  ENV{ID_V4L_CAPABILITIES}==":capture:"\
![image](https://user-images.githubusercontent.com/68049677/179949350-823ffcd1-1133-4dd1-9cbc-58db4302d22a.png)

**Comment by kate-goldenring** [comment]
Good find! We added the capture property to help with real camera discovery. We should modify the demo to add a note to add the capture property only if using real cameras. Would you be interested in putting in an update to the docs?

**Comment by leolumicrosoft** [comment]
Yes, I love to help. But the e2e demo document is in https://docs.akri.sh/ but not it this git repository. How shall I submit PR?

**Comment by kate-goldenring** [comment]
Great! You can put the PR into our [documentation repository](https://github.com/project-akri/akri-docs). Our site automatically will serve the changes. I looks like both the standard [demo](https://github.com/project-akri/akri-docs/blob/main/docs/demos/usb-camera-demo.md) and raspberry Pi [demo](https://github.com/project-akri/akri-docs/blob/8d5f62e3025f104b7fe40023decb2d4c5d0d213b/docs/demos/usb-camera-demo-rpi4.md) need to be modified

**Comment by kate-goldenring** [comment]
Thanks for putting in the fix @leolumicrosoft https://github.com/project-akri/akri-docs/pull/43! Marking as closed

**Comment by leolumicrosoft** [comment]
Sure, I am glad to take this task.
But the end to end document is in https://docs.akri.sh/demos/usb-camera-demo,

It is not in this Akri github repository, is it? How shall I raise PR for the document?

**Comment by kate-goldenring** [comment]
> Great! You can put the PR into our [documentation repository](https://github.com/project-akri/akri-docs). Our site automatically will serve the changes. I looks like both the standard [demo](https://github.com/project-akri/akri-docs/blob/main/docs/demos/usb-camera-demo.md) and raspberry Pi [demo](https://github.com/project-akri/akri-docs/blob/8d5f62e3025f104b7fe40023decb2d4c5d0d213b/docs/demos/usb-camera-demo-rpi4.md) need to be modified

@leolumicrosoft you can put it into the documentation repo

**Comment by leolumicrosoft** [comment]
It has been put into doc repository and the PR has been merged. I do not know why but it seems some of my old emails to github were sent again recently. Please ignore the repeated email reply and close this issue.
