### ISSUE TITLE
Unix domain socket (uds) gRPC-client implementation incompatible with Googles' C based gRPC (reference) implementation

### ISSUE THREAD

**Issue by bitmeal** [project-akri/akri#497]
**Describe the bug**
The unix domain socket implementation of the gRPC-client is incompatible with servers implemented using Googles' C based gRPC implementation. As this implementation is the base for most non-native implementations, it may be considered a **reference implementation** and this behavior is likely to be observable in a number of languages.

Discovery handlers implement the gRPC DiscoveryHandler service (as server) to be called by the akri agent. Using a unix domain socket as transport yields the following errors:
(C++ implementation; gRPC `1.48.0`; akri `0.8.4`):
```
# grpc server C++ / discovery handler
E0816 09:31:06.619375200      14 hpack_parser.cc:1235]       Error parsing metadata: error=invalid value key=:scheme value=dummy

# akri agent
[2022-08-16T09:31:06Z ERROR agent::util::discovery_operator] get_stream - could not connect to DiscoveryHandler at endpoint Uds("/var/lib/akri/demo-disco.sock") with error status: Unknown, message: "Bad :scheme header", details: [], metadata: MetadataMap { headers: {"content-type": "application/grpc"} }
```

***Analysis***
akri connects a gRPC-client over uds by instantiating a `tonic::transport::Endpoint` from a/the valid URL string `"dummy://[::]:50051"` and providing a `UnixStream` instance for the connection. *tonic* sets the `scheme` header from the URL provided at instantiation time, which results in `scheme: dummy`.  The C based implementation will reject all requests without `scheme` headers set to `http` or `https`:

https://github.com/grpc/grpc/blob/f268659bf183a39857064593b141f313845282d9/src/core/lib/transport/metadata_batch.cc#L150-L159

> *tonic* clients connecting over network are unaffected as all URLs are prefixed with `http://` in the current akri implementation

***Fix***
Replacing all instantiations of `tonic::transport::Endpoint` with URL `"dummy://[::]:50051"` to `"http://[::]:50051"`.

**See #498**

**To Reproduce**
* Build gRPC server listening on unix domain socket; using Google C based gRPC implementation
* Build rust gRPC client connecting to server over unix domain socket with akri-like implementation

**Expected behavior**
gRPC communication working and no errors thrown. I.e.: Scheme header set correctly.

**Logs (please share snips of applicable logs)**
```
# grpc server C++ / discovery handler
E0816 09:31:06.619375200      14 hpack_parser.cc:1235]       Error parsing metadata: error=invalid value key=:scheme value=dummy

# akri agent
[2022-08-16T09:31:06Z ERROR agent::util::discovery_operator] get_stream - could not connect to DiscoveryHandler at endpoint Uds("/var/lib/akri/demo-disco.sock") with error status: Unknown, message: "Bad :scheme header", details: [], metadata: MetadataMap { headers: {"content-type": "application/grpc"} }
```

**Comment by kate-goldenring** [comment]
@bitmeal thank you for looking into this and putting in the fix.
