### ISSUE TITLE
Create workflow to update version on behalf of contributor 

### ISSUE THREAD

**Issue by kate-goldenring** [project-akri/akri#500]
**Is your feature request related to a problem? Please describe.**
Recently switched to the mac world and there are some [issues with sed compatibility](https://stackoverflow.com/questions/4247068/sed-command-with-i-option-failing-on-mac-but-works-on-linux) with Akri's [`version.sh`](https://github.com/project-akri/akri/blob/main/version.sh) script.

Rather than modifying the script for various OSes, it would be nice to have a workflow that will increase the version on behalf of the contributor. Instead/in addition to a [version check workflow](https://github.com/project-akri/akri/blob/main/.github/workflows/check-versioning.yml), we could have a version bump workflow that increases the version according to PR labels. 

> Note: for other mac users, updating `sed -i s/"$LINE_PATTERN"/"$NEW_LINE"/g $FILE` and `sed -i "/$LINE1_PATTERN/ {n;/$LINE2_PATTERN/ {s/$LINE2_PATTERN/$NEW_LINE2/;p;d;}}" $FILE` to use `perl` instead as `perl -i -pes/"$LINE_PATTERN"/"$NEW_LINE"/g $FILE` and `perl -i -pe"/$LINE1_PATTERN/ {n;/$LINE2_PATTERN/ {s/$LINE2_PATTERN/$NEW_LINE2/;p;d;}}" $FILE` make the script successfully update the version (with some warnings).

**Comment by Rishit-dagli** [comment]
I would love to take this up
