### ISSUE TITLE
Ensure `cargo tarpaulin` is using same Rust version as Akri

### ISSUE THREAD

**Issue by kate-goldenring** [project-akri/akri#501]
**Describe the bug**
Akri's code coverage checks with `cargo tarpaulin` are [currently failing](https://github.com/project-akri/akri/runs/7882109843?check_suite_focus=true#step:7:887) because `cargo tarpaulin` is using the `1.63` rust toolchain while Akri is using `1.61`.

`cargo tarpaulin` [should be inferring Rust version](https://github.com/xd009642/tarpaulin#environment-variables) from the Cargo.toml. However, instead of checking each package's `Cargo.toml` (see the [agent's](https://github.com/project-akri/akri/blob/main/agent/Cargo.toml#L6)) and installing and using a potentially different toolchain for each, it may just be checking the base `Cargo.toml`. However, since [our base toml](https://github.com/project-akri/akri/blob/main/Cargo.toml) represents the larger workspace of projects, it [cannot specify a version](https://doc.rust-lang.org/cargo/reference/manifest.html#the-manifest-format), so it appears that tarpaulin just uses latest stable in this case. 

Investigation should be done as to whether the [`CARGO_PACKAGE_VERSION`](https://github.com/xd009642/tarpaulin#environment-variables) env var can be explicitly set to a specific rust version in the workflow when [running tarpaulin in a container](https://github.com/project-akri/akri/blob/2b42eb28a41aaab966eb2823a693464153a127ee/.github/workflows/run-tarpaulin.yml#L39).

**Comment by adithyaj** [comment]
I'll take this one, I'll try to see if we can set the env var itself and worst case we can update rust and move forward for now.

**Comment by bfjelds** [comment]
i wonder if you couldn't do something like this:

```
docker exec $(cat container_id.txt) sh -c "rustup install 1.61.0"
docker exec $(cat container_id.txt) sh -c "rustup override set 1.61.0"
```

**Comment by bfjelds** [comment]
> i wonder if you couldn't do something like this:
> 
> ```
> docker exec $(cat container_id.txt) sh -c "rustup install 1.61.0"
> docker exec $(cat container_id.txt) sh -c "rustup override set 1.61.0"
> ```

seems to work.  i created this PR: https://github.com/project-akri/akri/pull/503 ... when i cherry-picked the changes onto https://github.com/project-akri/akri/pull/498, the tarpaulin run succeeded: https://github.com/project-akri/akri/runs/8102394108?check_suite_focus=true

**Comment by adithyaj** [comment]
Thanks Brian!
