### ISSUE TITLE
The requested image's platform (linux/amd64) does not match the detected host platform (linux/riscv64) and no specific platform was requested

### ISSUE THREAD

**Issue by advancedwebdeveloper** [project-akri/akri#512]
Tried to build your project, on a 64bit RISC-V board:

> $ make
> docker build  -f build/containers/intermediate/Dockerfile.opencvsharp-build . -t devcaptest.azurecr.io/ubuntu/opencvsharp-build:0.0.9-amd64 --build-arg PLATF
> ORM_TAG=3.1-buster-slim
> Sending build context to Docker daemon  117.2kB
> Step 1/25 : ARG PLATFORM_TAG=3.1-buster-slim
> Step 2/25 : FROM mcr.microsoft.com/dotnet/core/aspnet:${PLATFORM_TAG} AS base
> 3.1-buster-slim: Pulling from dotnet/core/aspnet
> 4b7b4a8876e2: Pull complete 
> a999ea1c59c9: Pull complete 
> c3fe5253e376: Pull complete 
> 9816ec06a472: Pull complete 
> f73858caf662: Pull complete 
> Digest: sha256:38d498dc1e3feccec9aed2ca1109ad8ba120f6c2628cdfe2c6f633654632b9f0
> Status: Downloaded newer image for mcr.microsoft.com/dotnet/core/aspnet:3.1-buster-slim
>  ---> 4e91386248ba
> Step 3/25 : WORKDIR /app
>  ---> [Warning] The requested image's platform (linux/amd64) does not match the detected host platform (linux/riscv64) and no specific platform was requested
>  ---> Running in 8c4a7dff4305
> Removing intermediate container 8c4a7dff4305
>  ---> cd5567a123b7
> Step 4/25 : LABEL org.opencontainers.image.source https://github.com/project-akri/akri
>  ---> [Warning] The requested image's platform (linux/amd64) does not match the detected host platform (linux/riscv64) and no specific platform was requested
>  ---> Running in 638127d97288
> Removing intermediate container 638127d97288
>  ---> 3678e433a391
> Step 5/25 : ENV OPENCV_VERSION="4.5.4"
>  ---> [Warning] The requested image's platform (linux/amd64) does not match the detected host platform (linux/riscv64) and no specific platform was requested
>  ---> Running in 5f7703cef92e
> Removing intermediate container 5f7703cef92e
>  ---> a56c8306c3c0
> Step 6/25 : ENV OPENCV_INSTALLATION_DIR="/opt/opencv/"
>  ---> [Warning] The requested image's platform (linux/amd64) does not match the detected host platform (linux/riscv64) and no specific platform was requested
>  ---> Running in b18cbde03531
> Removing intermediate container b18cbde03531
>  ---> 0a9eb69843ae
> Step 7/25 : ENV OPENCV_SHARP_VERSION="4.5.3.20210821"
>  ---> [Warning] The requested image's platform (linux/amd64) does not match the detected host platform (linux/riscv64) and no specific platform was requested
>  ---> Running in a8edf9fa34dd
> Removing intermediate container a8edf9fa34dd
>  ---> 89fbf6a58748
> Step 8/25 : RUN whoami
>  ---> [Warning] The requested image's platform (linux/amd64) does not match the detected host platform (linux/riscv64) and no specific platform was requested
>  ---> Running in f5342d2140a7
> standard_init_linux.go:219: exec user process caused: exec format error
> The command '/bin/sh -c whoami' returned a non-zero code: 1
> make: *** [build/intermediate-containers.mk:21: opencv-base-build-amd64] Error 1
>

**Comment by gorodion** [comment]
Same problem. I think it's because WSL2 is installed

**Comment by kate-goldenring** [comment]
@advancedwebdeveloper  have you been able to build the other container? The opencvsharp container is just for one of our demo brokers, so I'd recommend using one of the released images instead, unless there is some reason you want to build your own. I would narrow down your build to only building the containers you want to build: https://docs.akri.sh/development/development#build-akri-component-containers.

**Comment by kate-goldenring** [comment]
@gorodion and @advancedwebdeveloper do we want to keep this alive to track WSL2 and or RISC-V support for making Akri containers? Or do this developer docs help with creating the containers you need for the platforms you are using: https://docs.akri.sh/development/development#build-akri-component-containers
