### ISSUE TITLE
Update build agents to latest container dependency versions

### ISSUE THREAD

**Issue by adithyaj** [project-akri/akri#524]
**Is your feature request related to a problem? Please describe.**
GitHub Actions is getting rid of their older ubuntu build agent containers this December. Our build agent containers use Ubuntu 18.04 and we may have certain references that may need to be changed. For example:
<pre><code>echo "deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-<b>xenial</b> main" | sudo tee /etc/apt/sources.list.d/kubernetes.list</code></pre>

[Link to older version deprecation](https://github.blog/changelog/2022-08-09-github-actions-the-ubuntu-18-04-actions-runner-image-is-being-deprecated-and-will-be-removed-by-12-1-22/)

**Comment by lunchboxav** [comment]
Hi, I'm interested in working on this. Can you provide some pointers on where should I get started?

**Comment by kate-goldenring** [comment]
@adithyaj, i am not sure i follow the issue. It looks like we are pointing to `ubuntu-latest` in our builds, and `kubernetes-xenial` seems to be the default for [Kubernetes installs](https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/#installing-kubeadm-kubelet-and-kubectl) (id assume on latest ubuntu).

**Comment by jbpaux** [comment]
This one seems to use 18.04:
https://github.com/project-akri/akri/blob/ed6446a659925334d4da851577a5e620f447aa32/.github/workflows/run-test-cases.yml#L48
This one too:
https://github.com/project-akri/akri/blob/ed6446a659925334d4da851577a5e620f447aa32/.github/workflows/run-test-cases.yml#L99
This one is using 20.04 (not latest):
https://github.com/project-akri/akri/blob/ed6446a659925334d4da851577a5e620f447aa32/.github/workflows/update-versions.yml#L10

**Comment by kate-goldenring** [comment]
@lunchboxav are you still interested in taking this on? Changing the above workflows to latest would be a great add.

**Comment by adithyaj** [comment]
> This one seems to use 18.04:
> 
> https://github.com/project-akri/akri/blob/ed6446a659925334d4da851577a5e620f447aa32/.github/workflows/run-test-cases.yml#L48
> 
> 
> This one too:
> https://github.com/project-akri/akri/blob/ed6446a659925334d4da851577a5e620f447aa32/.github/workflows/run-test-cases.yml#L99
> 
> 
> This one is using 20.04 (not latest):
> https://github.com/project-akri/akri/blob/ed6446a659925334d4da851577a5e620f447aa32/.github/workflows/update-versions.yml#L10

@lunchboxav That's correct, those workflows should use 20.04 and that would require the change just as you mentioned. We could try to use the `ubuntu-latest` for all the workflows instead of pinning it to a particular ubuntu version which would be a nice change but we should be wary of any diffs between the two.

Also FYI - I mentioned this issue in #537 since it's a similar issue (node dependency) that would also be super helpful to resolve
