### ISSUE TITLE
Controller crashing when akri config is bad

### ISSUE THREAD

**Issue by aluedeke** [project-akri/akri#525]
What I have experienced:

I deployed a bad akri configuration which made my akri controller crash. I don't believe this should happen:

Akri config (obviously broken):
```
apiVersion: akri.sh/v0
kind: Configuration
metadata:
  name: akri-adb
spec:
  discoveryHandler:
    name: usb
    discoveryDetails: |+
      class: 0xff
      subClass: 0x42
      protocol: 0x1
  brokerSpec:
    brokerPodSpec:
      setHostnameAsFQDN: true
      containers:
      - name: akri-adb-broker
        image: v4l:latest
        securityContext:
          privileged: true
        resources:
          requests:
            "{{' }}PLACEHOLDER{{ '}}' }}" : "1"
            memory: 10Mi
            cpu: 10m
          limits:
            "{{ '{{' }}PLACEHOLDER{{ '}}' }}" : "1"
            memory: 30Mi
            cpu: 29m
  instanceServiceSpec:
    type: ClusterIP
    ports:
    - name: grpc
      port: 80
      protocol: TCP
      targetPort: 8083
  configurationServiceSpec:
    type: ClusterIP
    ports:
    - name: grpc
      port: 80
      protocol: TCP
      targetPort: 8083
  brokerProperties: {}
  capacity: 1
```

this led to the following logs:
```
[2022-09-30T09:42:15Z TRACE akri_shared::k8s::pod] create_pod enter
[2022-09-30T09:42:15Z INFO  akri_shared::k8s::pod] create_pod pods.create(...).await?:
[2022-09-30T09:42:15Z ERROR akri_shared::k8s::pod] create_pod pods.create [Ok("{\"apiVersion\":\"v1\",\"kind\":\"Pod\",\"metadata\":{\"labels\":{\"akri.sh/configuration\":\"akri-adb\",\"akri.sh/instance\":\"akri-adb-4e943c\",\"akri.sh/target-node\":\"k3d-nucdev-server-0\",\"app\":\"akri-adb-4e943c-pod\",\"controller\":\"akri.sh\"},\"name\":\"akri-adb-4e943c-pod\",\"namespace\":\"rdc\",\"ownerReferences\":[{\"apiVersion\":\"akri.sh/v0\",\"blockOwnerDeletion\":true,\"controller\":true,\"kind\":\"Instance\",\"name\":\"akri-adb-4e943c\",\"uid\":\"a74a8e30-9c36-4a11-a5a0-0c4b5fe47c5f\"}]},\"spec\":{\"affinity\":{\"nodeAffinity\":{\"requiredDuringSchedulingIgnoredDuringExecution\":{\"nodeSelectorTerms\":[{\"matchFields\":[{\"key\":\"metadata.name\",\"operator\":\"In\",\"values\":[\"k3d-nucdev-server-0\"]}]}]}}},\"containers\":[{\"image\":\"quay.io/saucelabs/v4l:713aa3bc\",\"name\":\"akri-adb-broker\",\"resources\":{\"limits\":{\"cpu\":\"29m\",\"memory\":\"30Mi\",\"{{ '{{' }}PLACEHOLDER{{ '}}' }}\":\"1\"},\"requests\":{\"cpu\":\"10m\",\"memory\":\"10Mi\",\"{{ '{{' }}PLACEHOLDER{{ '}}' }}\":\"1\"}},\"securityContext\":{\"privileged\":true}}]}}")] returned kube error: ErrorResponse { status: "Failure", message: "Pod \"akri-adb-4e943c-pod\" is invalid: [spec.containers[0].resources.limits[{{ '{{' }}PLACEHOLDER{{ '}}' }}]: Invalid value: \"{{ '{{' }}PLACEHOLDER{{ '}}' }}\": name part must consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyName',  or 'my.name',  or '123-abc', regex used for validation is '([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9]'), spec.containers[0].resources.limits[{{ '{{' }}PLACEHOLDER{{ '}}' }}]: Invalid value: \"{{ '{{' }}PLACEHOLDER{{ '}}' }}\": must be a standard resource for containers, spec.containers[0].resources.requests[{{ '{{' }}PLACEHOLDER{{ '}}' }}]: Invalid value: \"{{ '{{' }}PLACEHOLDER{{ '}}' }}\": name part must consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyName',  or 'my.name',  or '123-abc', regex used for validation is '([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9]'), spec.containers[0].resources.requests[{{ '{{' }}PLACEHOLDER{{ '}}' }}]: Invalid value: \"{{ '{{' }}PLACEHOLDER{{ '}}' }}\": must be a standard resource for containers]", reason: "Invalid", code: 422 }
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Pod "akri-adb-4e943c-pod" is invalid: [spec.containers[0].resources.limits[{{ '{{' }}PLACEHOLDER{{ '}}' }}]: Invalid value: "{{ '{{' }}PLACEHOLDER{{ '}}' }}": name part must consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyName',  or 'my.name',  or '123-abc', regex used for validation is '([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9]'), spec.containers[0].resources.limits[{{ '{{' }}PLACEHOLDER{{ '}}' }}]: Invalid value: "{{ '{{' }}PLACEHOLDER{{ '}}' }}": must be a standard resource for containers, spec.containers[0].resources.requests[{{ '{{' }}PLACEHOLDER{{ '}}' }}]: Invalid value: "{{ '{{' }}PLACEHOLDER{{ '}}' }}": name part must consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyName',  or 'my.name',  or '123-abc', regex used for validation is '([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9]'), spec.containers[0].resources.requests[{{ '{{' }}PLACEHOLDER{{ '}}' }}]: Invalid value: "{{ '{{' }}PLACEHOLDER{{ '}}' }}": must be a standard resource for containers]: Invalid', controller/src/util/instance_action.rs:82:18
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: JoinError::Panic(...)', controller/src/main.rs:48:64
Error: JoinError::Panic(...)
```
I believe the following unwrap is the culprit here:
https://github.com/project-akri/akri/blob/befa9435f15b84391d104668c450d8ec0a545493/controller/src/main.rs#L48

**Comment by kate-goldenring** [comment]
@aluedeke how did you create your configuration? Was it with the Helm charts? The CPU and memory placeholders should look like the following: ` "{{PLACEHOLDER}}" : "1"` This is used by the controller to insert requests for the discovered devices ([see this note on custom configs](https://docs.akri.sh/user-guide/customizing-an-akri-installation#generating-modifying-and-applying-a-configuration)). 

Are you saying it would be preferable for the controller to not error out upon a bad configuration application rather ignore it?

**Comment by aluedeke** [comment]
@kate-goldenring I messed up the config manually and fixed it already, so absolutetly my bad. Nevertheless, I am concerned that a single broken config can mess up my whole akri deployment. I would expect Akri to just log an error in case it receives a broken config. I wouldn't expect a crash.

> Are you saying it would be preferable for the controller to not error out upon a bad configuration application rather ignore it?

Yes absolutely.

**Comment by kate-goldenring** [comment]
@aluedeke makes sense. we originally chose to error out to ensure the user knows it is in a broken state and we created a Webhook to help with detecting and preventing the application of bad Configurations: https://github.com/project-akri/akri/tree/main/webhooks/validating/configuration

But we also dont publicize the webhook quite enough. Do you think that the webhook solves the issue or would it still be better to error out?

**Comment by kate-goldenring** [comment]
@bfjelds do you think logging malformed configs rather than erroring out would be a good switch?

**Comment by diconico07** [comment]
I really don't think crashing is a good idea, if you have say 10 Configuration resources and one is wrong (or became wrong), you don't want the controller to stop provisioning the workload for the other ones.

I think it would be better to at least publish an Event (an additional log line won't hurt, but is less visible to the user).

Ideally it would have a status on the Configuration resources with a Condition on whether the controller correctly processed it allowing to display some kind of error message to the user if there is an issue with the broker specs, but that can be done later on.
In fact this status could also be used with other conditions to tell about the overall status of created broker pods or by the Agent as well to tell that the Configuration got handled by a discovery handler for example, so it can be a part of a broader discussion about feedback to the user about Akri's resources.

From my point of view, when dealing with Configuration related runtime errors, we should allow the user to be aware of this when looking at the resource, and it shouldn't impact other Configuration resources.

**Comment by diconico07** [comment]
I took a closer look into the `Configuration` validation webhook, it only checks that the `Configuration` resource follows the specs, so in the reported bug it wouldn't change anything.

In order to have the webhook catch this kind of error, we would have to do a dry-run pod creation using the given specs to see if the pod admission controllers would be accepting the generated manifest.

And we would actually have the same need for many of the parts that aren't currently checked by the webhook like job/service creation, discovery handler specific configuration, and I'm probably missing some.

Moreover this wouldn't be enough as this would not prevent TOCTOU issues (like a change of pod admission rules between the admission of the `Configuration` and the creation of the broker pod).

**Comment by bfjelds** [comment]
> @bfjelds do you think logging malformed configs rather than erroring out would be a good switch?

I'm pretty late to this, but I think the crash actually helps more than the resiliency does.  But I certainly understand the other side.

**Comment by diconico07** [comment]
> > @bfjelds do you think logging malformed configs rather than erroring out would be a good switch?
> 
> I'm pretty late to this, but I think the crash actually helps more than the resiliency does. If the system went on happily, someone might be more inclined to think that everything was fine, but there were no devices found.
> 
> That said, I certainly understand the other side: passing 1 bad config shouldn't impact other configs.

That's why I think we need to add a status field to `Instances` and `Configurations` so we provide visible feedback to the user when there is a bad config or an issue with creating the broker for a given instance.
