### ISSUE TITLE
docs.akri.sh is down?

### ISSUE THREAD

**Issue by johnliu55-msft** [project-akri/akri#544]
**Describe the bug**

I can't seem to connect to https://docs.akri.sh. DNS resolve failed with `SERVFAIL`:

![image](https://user-images.githubusercontent.com/107901166/208623156-9b1af20f-f192-4aa0-925d-513d494f8a6b.png)

**Comment by kate-goldenring** [comment]
@johnliu55-msft, thank you for bringing this up. We need to update our CNAME record with the CNCF and are actively working to make the docs available. In the mean time, Markdown docs can be found here https://github.com/project-akri/akri-docs/tree/main/docs. @adithyaj can you post any updates here?

**Comment by adithyaj** [comment]
Thanks @johnliu55-msft! 
We filled a ticket with the CNCF to update the CNAME record for our docs. Once I hear back I'll post updates here (and we can use this issue to track the status).

**Comment by adithyaj** [comment]
Updating here - got confirmation that they got the request and the webhost maintainer on their side is on vacation. We will work with them to get this back up once they get back shortly.

**Comment by adithyaj** [comment]
I worked with them yesterday and today so this should be resolved, once the changes propagate and I see the domain back up I'll close this issue.

**Comment by kate-goldenring** [comment]
@adithyaj looks like the site is pointing to a spam site.

**Comment by adithyaj** [comment]
The old URL for gitbook seemed to have lapsed and pointed to a spam site so when it was restored it pointed to it. We immediately took the domain down again and are slowly starting to spin back up with the new URL.

Sorry for the inconvenience!

**Comment by adithyaj** [comment]
The website is back up again! 🎉 

![image](https://user-images.githubusercontent.com/4684727/211938226-8db49d5a-e530-4c85-b685-396657b8cc87.png)
