### ISSUE TITLE
Is there any known date of next AKRI release?

### ISSUE THREAD

**Issue by rpieczon** [project-akri/akri#572]

**Comment by yujinkim-msft** [comment]
Hi @rpieczon! We are aiming for a new Akri release some time this month. If you'd like to learn more about the release, feel free to join our community meeting on April 4, 8AM PST. You can join our [slack](https://kubernetes.slack.com/archives/C01D9L7QE8Z) and find our meeting notes [here](https://hackmd.io/@akri/S1GKJidJd)!

**Comment by rpieczon** [comment]
Thanks for info!
