### ISSUE TITLE
Use Environment Files instead of `set-output` in GitHub workflows

### ISSUE THREAD

**Issue by kate-goldenring** [project-akri/akri#575]
We are getting depreciating warnings in our workflows (for example: https://github.com/project-akri/akri/actions/runs/4639914706):

```sh
The set-output command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
```

Support it being removed June 1, 2023. Looks like we do not directly use `set-output` so I wonder if we are bringing it in through one of the actions we use and simply need to update them. For example, bumping `actions/upload-artifact@v2` to `actions/upload-artifact@v3` may help

**Comment by jbpaux** [comment]
The PR related to updating GH actions should solve this too #548

**Comment by jbpaux** [comment]
You can close this issue, it's been resolved as you can see in the latest runs https://github.com/project-akri/akri/actions/runs/4723946299 🥳
