### ISSUE TITLE
Migrate away from using `actions-rs`

### ISSUE THREAD

**Issue by kate-goldenring** [project-akri/akri#579]
We are updating to latest node versions in https://github.com/project-akri/akri/pull/548; however, `actions-rs` actions [(audit-check](https://github.com/actions-rs/audit-check) and [toolchain)](https://github.com/actions-rs/toolchain) don't have node16 compatible versions available and the maintainer is gone. @jbpaux advises to switch to other actions-- for example the toolchain: the [dtolnay/rust-toolchain](https://github.com/dtolnay/rust-toolchain) one but none for the audit-check.

**Comment by jbpaux** [comment]
I just saw https://github.com/rustsec/audit-check is a maintained fork for `audit-check` so we can switch to that.
