### ISSUE TITLE
Akri controller not running on master node in master+worker node scenario

### ISSUE THREAD

**Issue by leeyun53** [project-akri/akri#592]
**Describe the bug**
When running Akri on two machines (a control plane and a worker node), Akri controller resides in worker node. However, it says in the [Akri doc](https://docs.akri.sh/architecture/controller-in-depth) that "the Akri Controller executes on the master Node in the cluster". This is how the Akri controller is set to be now in [akri/values.yaml](https://github.com/project-akri/akri/blob/main/deployment/helm/values.yaml) like the following:

```
  ...
  # onlyOnControlPlane dictates whether the Akri Controller will only run on nodes with 
  # the label with (key, value) of ("node-role.kubernetes.io/master", "")
  onlyOnControlPlane: false
  # allowOnControlPlane dictates whether a toleration will be added to allow to Akri Controller 
  # to run on the control plane node
  allowOnControlPlane: true
  # linuxOnly dictates whether the Akri Controller will only run on a linux node
  ...
```

**Output of `kubectl get pods,akrii,akric -o wide`**
```
PS C:\Users\> kubectl get nodes
NAME                    STATUS   ROLES           AGE     VERSION
bb3-ledge   Ready       control-plane   7d21h   v1.24.6
bb5-ledge   Ready       <none>          7d21h   v1.24.6

PS C:\Users\> kubectl get pods -o wide
NAME                                                     READY   STATUS    RESTARTS        AGE   IP              NODE        NOMINATED NODE   READINESS GATES
akri-agent-daemonset-lzmd4                               1/1     Running   1 (5d22h ago)   6d    10.244.77.26    bb5-ledge   <none>           <none>
akri-agent-daemonset-nsg7w                               1/1     Running   1 (5d22h ago)   6d    10.244.86.156   bb3-ledge   <none>           <none>
akri-controller-deployment-f654968c-jzg59                1/1     Running   2 (4d2h ago)    6d    10.244.77.27    bb5-ledge   <none>           <none>
akri-opcua-discovery-daemonset-ldpjj                     1/1     Running   1 (5d22h ago)   6d    10.244.77.24    bb5-ledge   <none>           <none>
akri-opcua-discovery-daemonset-pvr7c                     1/1     Running   1 (5d22h ago)   6d    10.244.86.152   bb3-ledge   <none>           <none>
bb3-ledge-akri-opcua-monitoring-ec2305-pod               0/1     Pending   0               6d    <none>          <none>      <none>           <none>
bb5-ledge-akri-opcua-monitoring-ec2305-pod               1/1     Running   1 (5d22h ago)   6d    10.244.77.25    bb5-ledge   <none>           <none>

PS C:\Users\> kubectl get akrii -o wide
NAME                           CONFIG                  SHARED   NODES                       AGE
akri-opcua-monitoring-ec2305   akri-opcua-monitoring   true     ["bb5-ledge","bb3-ledge"]   6d

PS C:\Users\> kubectl get akric -o wide
NAME                    CAPACITY   AGE
akri-opcua-monitoring   1          6d
```

**Kubernetes Version: k8s**

**To Reproduce**
1. Create cluster with a master node and a worker node
2. Install Akri 

**Expected behavior**
The Akri controller should reside on a control plane (master) node not on a worker node.

**Comment by agracey** [comment]
You need to set ```onlyOnControlPlane: false``` to be ```onlyOnControlPlane: true```. Without this, there is no constraint on where the pod will reside and it will float around.

**Comment by agracey** [comment]
Out of curiosity, why do you want the controller pod to be constrained? It should load balance to which ever node has space.

**Comment by leeyun53** [comment]
I see, so it is intentionally set to be `onlyOnControlPlane: false` for a load balancing purpose. FYI I wanted to get controller information from a control plane's journald.

**Comment by kate-goldenring** [comment]
Closing this as it appears to be resolved. We have some documentation on this here https://docs.akri.sh/user-guide/getting-started#customizing-where-the-controller-runs. @leeyun53 feel free to put in a PR to update these docs too. They may be out of date.
