### ISSUE TITLE
agent-registration.sock and udev.sock socket files world readable

### ISSUE THREAD

**Issue by huornlmj** [project-akri/akri#683]
**Describe the bug**
Socket files are world readable on the host.  This means that a limited user account on the host can read from the socket files that both containers use to converse with each other when they shouldn't have this permission.  Is there a plan to make the world bit '0'?
```console
ubuntu@localhost:~$ ls -la /var/lib/akri/agent-registration.sock
srwxr-xr-x 1 root root 0 Dec  7 10:40 /var/lib/akri/agent-registration.sock
```

**Comment by diconico07** [comment]
You can't do anything with a RO unix stream socket, so I don't see the issue there
