### ISSUE TITLE
Put Akri on Adoption List of Related Projects

### ISSUE THREAD

**Issue by kate-goldenring** [project-akri/akri#688]
- Get us listed on Kube RS adoption: https://kube.rs/adopters/
- Get us listed under [device plugin interface](https://kubernetes.io/docs/concepts/extend-kubernetes/compute-storage-net/device-plugins/)

**Comment by yujinkim-msft** [comment]
@EthanChangAED

**Comment by EthanChangAED** [comment]
https://github.com/kube-rs/website/pull/59

**Comment by EthanChangAED** [comment]
Close as PRs are approved.
