### ISSUE TITLE
brokerJob uses brokerPod image tag 

### ISSUE THREAD

**Issue by melinda-mytra** [project-akri/akri#712]
**Describe the bug**
Because of these lines:
[udev](https://github.com/project-akri/akri/blob/ea2179627ae34700eaa5d2428b1ddfbb50893440/deployment/helm/templates/udev-configuration.yaml#L75C1-L76C1)
[custom](https://github.com/project-akri/akri/blob/ea2179627ae34700eaa5d2428b1ddfbb50893440/deployment/helm/templates/custom-configuration.yaml#L66)

Specified `.Values.[udev/custom].configuration.brokerJob.tag` is ignored, and `.Values.[udev/custom].configuration.brokerPod.tag` is used instead

**Expected behavior**
`.Values.[udev/custom].configuration.brokerJob.tag` is used to determine image tag for `brokerJob`

**Comment by kate-goldenring** [comment]
Thanks for finding this @melinda-mytra. Would you be willing to push up a fix?
