### ISSUE TITLE
Support IoT Plug and Play

### ISSUE THREAD

**Issue by martinp17** [project-akri/akri#88]
**Is your feature request related to a problem? Please describe.**
Microsoft IoT team has come up with a generic way to discover the resources such as temperature sensors or whatever. It would be great if Akri could just discover such resources.

**Is your feature request related to a way you would like Akri extended? Please describe.**
For each IoT P&P device, it would be great if Akri would create a resource handler automatically.

**Additional context**
For details, see https://docs.microsoft.com/en-us/azure/iot-pnp/

**Comment by jiria** [comment]
Hello @martinp17,

Agreed that IoT Plug and Play should fit well with Akri. We have [a doc on adding additional protocols](https://github.com/deislabs/akri/blob/main/docs/extensibility.md#contributing-your-protocol-implementation-back-to-akri). If you have some ideas, feel free to start on step 2 to create the proposal or share your ideas here.
